apiVersion: v1
kind: ConfigMap
metadata:
  name: springboot-db-config
data:
  application.properties: |
    spring.datasource.url=jdbc:mysql://db-host:3306/your_database
    spring.datasource.username=db_username
    spring.datasource.password=db_password
    # other database configurations
