apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot
        image: 123ars/spring-boot:new-version  # Update to the new version
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1   # Maximum number of unavailable pods during the update
      maxSurge: 1         # Maximum number of additional pods to create during the update
  volumes:
  - name: config-volume
    configMap:
      name: springboot-db-config
