apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: spring-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: spring-deployment
 minReplicas: 1
 maxReplicas: 4
 targetCPUUtilizationPercentage: 60
