apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
    app: springboot
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast
  awsElasticBlockStore:
    volumeID: vol-0d8abfb80dd8aa325  # ebs volumeid 
    fsType: ext4

