kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spring-app-role-binding
subjects:
- kind: ServiceAccount
  name: spring-app-service-account
roleRef:
  kind: Role
  name: spring-app-role
  apiGroup: rbac.authorization.k8s.io
